PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX gn: <http://www.geonames.org/ontology/>
PREFIX gc: <http://www.oegov.org/core/owl/gc>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns>
PREFIX foaf: <http://xmlns.com/foaf/0.1>

CONSTRUCT {
?country dbo:isoCode ?code;
	gn:name ?longName;
	gn:shortName ?shortName;
	dbo:region ?region;
	dbo:income ?income;
	gc:currency ?currency;
	dbo:indicator _:y.
_:y rdf:value ?value;
	gc:year ?year;
	foaf:name ?indicatorName;
	dbo:code ?indicatorCode
}
FROM <file:test.csv>
WHERE {
BIND (URI(CONCAT('http://dbpedia.org/page/', REPLACE(xsd:string(?shortName), " ", "_"))) AS ?country)
BIND (xsd:string(?CountryCode) AS ?code)
BIND (xsd:string(?LongName) AS ?longName)
BIND (xsd:string(?ShortName) AS ?shortName)
BIND (xsd:string(?Region) AS ?region)
BIND (xsd:string(?IncomeGroup) AS ?income)
BIND (xsd:string(?CurrencyUnit) AS ?currency)
BIND (xsd:string(?IndicatorName) AS ?indicatorName)
BIND (xsd:string(?IndicatorCode) AS ?indicatorCode)
BIND (xsd:integer(?Year) AS ?year)
BIND (xsd:decimal(?Value) AS ?value)
}
